---
- name: Configure Managed Nodes
  hosts: manage_nodes
  become: yes
  become_user: root

  tasks:
    - name: Ensure Python 3 and pip3 are installed
      raw: "apt-get update && apt-get -y install python3 python3-pip"

    - name: Use pip3 as the default pip
      command: update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

    - name: Use Python 3 as the default Python
      command: update-alternatives --install /usr/bin/python python /usr/bin/python3 1

    - name: Install OpenJDK
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Create MOTD file
      template:
        src: motd.j2
        dest: /home/victor/PrelimCPE232
      vars:
        motd_text: "{{ motd_message | default('Ansible Managed node by ' Ortega) }}"

    - name: Create a user
      user:
        name: "{{ ortega }}"
        state: present
      vars:
        user_name: "{{ user_config.ortega }}"
