---
- name: Configure Managed Nodes
  hosts: managed_nodes
  become: yes
  vars_files:
    - config.yaml
  tasks:
    - name: Install Python3 and pip3
      apt:
        name: ['python3', 'python3-pip']
        state: present
      become: yes

    - name: Set pip3 as default pip
      alternatives:
        name: /usr/bin/pip
        path: /usr/bin/pip3

    - name: Set python3 as default python
      alternatives:
        name: /usr/bin/python
        path: /usr/bin/python3

    - name: Install OpenJDK
      apt:
        name: openjdk-11-jdk
        state: present
      become: yes

    - name: Set MOTD (Message of the Day)
      template:
        src: motd.j2
        dest: /etc/motd
      become: yes

    - name: Create User
      user:
        name: "{{ user_name }}"
        state: present
        shell: /bin/bash
      become: yes
