---
- hosts: all
  tasks:
  - name: Install Python 3
    apt:
      name: python3
      state: present

  - name: Install Pip 3
    apt:
      name: python3-pip
      state: present

  - name: Make Pip 3 the default pip
    command:
      cmd: sudo update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

  - name: Make Python 3 the default python
    command:
      cmd: sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1

  - name: Install Java OpenJDK
    apt:
      name: openjdk-11-jdk
      state: present

  - name: Create Motd
    lineinfile:
      dest: /etc/motd
      line: "{{ ansible_hostname }} is an Ansible managed node by {{ ansible_user }}"
      when: motd is not defined or motd == ""

  - name: Create User
    user:
      name: "{{ user_name }}"
      state: present
      createhome: yes
