---
 - hosts: all
   become: true
   tasks:

   - name: install python3 and pip3 for ubuntu
     package:
       name:
         - python3
         - python3-pip
       state: latest
       update_cache: yes
     when: ansible_distribution == "Ubuntu"

   - name: install python3 and pip3 for Centos
     package:
        name:
          - python3
          - python3-pip
        state: latest
        update_cache: yes
     when: ansible_distribution == "Centos"

   - name: install java for ubuntu
     package:
       name:
         - openjdk-17-jdk
       state: latest
       update_cache: yes
     when: ansible_distribution == "Ubuntu"

   - name: install java openjdk for Centos
     yum:
        name:
          - java-11-openjdk
        state: latest
        update_cache: yes
     when: ansible_distribution == "Centos"

   - name: Motd message
     lineinfile:
       path: /etc/motd
       line: "{{ Welcome! Ansible Managed Node by Ortega | default('Ansible Managed Node by ' + ansible_user) }}"
     register: motd_result
     when: motd_message is defined

   - name: Set Default Motd message
     lineinfile:
       path: /etc/motd
       line: "Ansible Managed node by {{ ansible_user }}"
     when: motd_message is not defined

   - name: Display Motd result
     debug:
       msg: "{{ lookup('file', '/etc/motd') }}"

   - name: Create a new user
     user:
       name: "{{ new_username }}"
       state: present
     when: new_username is defined


