---
- name: Configure Manage Nodes
  hosts: manage_nodes
  become: yes
  gather_facts: yes

  vars_files:
    - config.yaml

  tasks:
    - name: Update apt cache (Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install python3 and pip3
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - python3
        - python3-pip
      when: ansible_os_family == "Debian"

    - name: Set python3 as default python
      alternatives:
        name: python
        path: /usr/bin/python3
      when: ansible_os_family == "Debian"

    - name: Install OpenJDK (Java)
      package:
        name: openjdk-11-jdk
        state: present
      when: ansible_os_family == "Debian"

    - name: Set MOTD
      copy:
        content: "{{ motd_text | default('Ansible Managed node by ' + Ortega) }}"
        dest: /home/victor/PrelimCPE232
      when: ansible_os_family == "Debian"

    - name: Create User
      user:
        name: "{{ new_username }}"
        state: present
        shell: /bin/bash
      when: ansible_os_family == "Debian"
